In [1]:
from google.colab import drive
from google.colab import data_table

drive.mount('/content/drive')
data_table.enable_dataframe_formatter()
file_path = "/content/drive/MyDrive/Virtual Reality Lesson and Community Smells/Questionari/csv/"

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.ticker as ticker
import seaborn as sns
import os
from os import path

## Merge into one dataset to perform the operations

We added a column at the end indicating from which of the three datasets the original answer was from.

Then, we merge the dataset.

In [3]:
file_name_1 = "Presenza_Pre_Normalizzazione.csv"
file_name_2 = "Remoto_Pre_Normalizzazione.csv"
file_name_3 = "VR_Pre_Normalizzazione.csv"

df_presenza = pd.read_csv(file_path+file_name_1)
df_presenza["Dataset"] = "Presence"

df_remote = pd.read_csv(file_path+file_name_2)
df_remote["Dataset"] = "Remote"

df_vr = pd.read_csv(file_path+file_name_3)
df_vr["Dataset"] = "VR"

# Dataset merge
df = pd.concat([df_presenza, df_remote, df_vr])
df

Warning: Total number of columns (57) exceeds max_columns (20). Falling back to pandas display.

,Cos'è il Social Debt?,Quale delle seguenti affermazioni descrive meglio un anti-pattern socio-tecnico?,Cosa sono i community smells?,Come differiscono i community smells dai code smells?,Qual è un esempio di community smell?,Quale affermazione sulla gestione del Social Debt è vera?,Qual è la principale differenza tra anti-pattern socio-tecnici e anti-pattern sociali,Cosa significa il termine 'Radio Silence' nel contesto dei community smells?,Vero o falso: Il Social Debt si riferisce solo ai costi finanziari di un progetto software.,Vero o falso: Gli anti-pattern socio-tecnici possono portare all'accumulo di Social Debt.,...,Durante la lezione ho lasciato che la mia mente vagasse.,Ho fatto finta di seguire la lezione.,Quanta attività mentale e percettiva ritieni sia stata richiesta durante la lezione? (Molto Semplice Da Seguire - Molto Impegnativa Da Seguire),Quanto è stata impegnativa fisicamente l’esperienza di seguire la lezione? (Molto Rilassante - Molto Faticosa),Come hai percepito il ritmo della lezione? Era lento o veloce? Sei riuscito/a a seguire l’esposizione dei concetti? (Nessuna Pressione - Molta Pressione),Valuta il tuo grado di soddisfazione riguardo alle tue prestazioni nell’ascoltare e comprendere la lezione (Massima Comprensione - Nessuna Comprensione),Quanto ti sei dovuto/a impegnare per mantenere un elevato livello di attenzione e comprensione durante la lezione? (Nessuno Sforzo - Massimo Sforzo),"Durante la lezione, come è variato il tuo livello di irritazione, stress e fastidio rispetto a quello di contentezza, relax e soddisfazione? (Massimo Relax - Massima Frustrazione)","Su una scala da 0 a 10, quante probabilità ci sono che parlerai positivamente di questa lezione sui 'Community Smells' a un amico o collega?",Dataset
0,1,1,1,1,1,1,1,1,1,1,...,1,1,9,10,10,10,8,10,10,Presence
1,1,1,1,1,1,1,1,1,1,1,...,1,1,8,10,7,3,7,9,8,Presence
2,1,1,1,1,1,1,1,1,0,1,...,3,1,9,9,10,9,8,10,8,Presence
3,1,1,1,1,1,1,1,0,0,1,...,1,1,9,10,10,10,9,10,8,Presence
4,0,1,1,1,1,1,1,1,1,1,...,1,1,9,10,8,9,10,9,10,Presence
5,1,1,1,1,1,1,1,1,1,0,...,2,1,9,9,10,9,9,10,10,Presence
6,1,1,1,1,1,1,1,1,1,1,...,2,2,10,10,10,10,10,10,9,Presence
7,1,1,1,1,1,1,1,1,1,1,...,2,1,6,7,7,8,8,8,7,Presence
8,1,1,1,1,1,1,1,1,1,1,...,2,1,5,9,6,9,5,9,8,Presence
9,1,1,1,1,1,1,1,1,1,1,...,5,2,6,7,7,8,5,6,8,Presence
0,1,1,1,1,1,1,1,1,1,1,...,2,1,9,10,10,8,9,10,9,Remote
1,1,1,1,1,1,1,1,1,1,1,...,2,1,9,9,10,9,9,10,8,Remote
2,1,1,1,1,1,1,1,1,1,1,...,2,1,8,9,9,9,9,8,8,Remote
3,1,0,1,1,1,1,1,1,1,0,...,3,1,8,9,5,4,7,9,2,Remote
4,1,1,1,1,1,1,1,1,1,1,...,2,1,4,9,6,10,7,9,8,Remote
5,1,1,1,1,1,1,1,1,0,1,...,3,2,5,7,10,3,8,10,8,Remote
6,1,1,1,1,1,1,1,1,1,1,...,1,1,4,10,7,9,9,10,9,Remote
7,1,1,1,1,1,1,1,1,1,1,...,2,1,6,7,8,9,8,7,9,Remote
8,1,1,1,1,1,1,1,1,0,1,...,3,1,4,8,6,8,9,10,7,Remote
9,1,1,1,1,1,1,1,1,1,1,...,1,1,9,9,10,9,9,9,9,Remote
0,1,1,1,1,1,1,1,0,1,1,...,1,1,9,10,10,10,10,10,10,VR
1,0,0,1,1,1,1,1,1,1,1,...,4,1,9,7,9,10,10,10,10,VR
2,1,1,1,1,1,1,1,1,0,1,...,1,1,4,4,10,8,4,4,10,VR
3,1,1,1,1,1,1,1,1,1,1,...,1,1,8,6,7,9,9,7,9,VR
4,1,1,1,1,1,1,1,1,1,1,...,5,2,7,9,9,7,5,8,9,VR
5,1,1,1,1,1,1,0,1,0,1,...,4,2,4,5,6,8,4,6,10,VR
6,1,1,1,1,1,1,1,1,0,1,...,2,1,6,7,8,4,6,10,10,VR
7,1,1,1,1,1,1,1,0,1,1,...,3,1,8,5,10,10,10,10,10,VR
8,1,1,1,1,1,1,1,1,1,1,...,1,1,5,10,8,10,10,8,6,VR
9,1,1,1,1,1,1,1,1,1,1,...,3,1,6,4,8,8,5,8,8,VR

In [4]:
variables = {
    "Learning Outcome": list(range(0, 13)),
    "Self Efficacy": list(range(13, 23)),
    "Immersiveness": list(range(23, 33)),
    "Affective Engagement": list(range(33, 38)),
    "Behavioral Engagement": list(range(38, 44)),
    "Cognitive Engagement": list(range(44, 46)),
    "Disengagement": list(range(46, 49)),
    "NASA-TLX": list(range(49, 55)),
    "NPS": [55]
}

variables_2 = {
    "Learning Outcome": list(range(0, 13)),
    "Self Efficacy": list(range(13, 23)),
    "Immersiveness": list(range(23, 33)),
    "Affective Engagement": list(range(33, 38)),
    "Behavioral Engagement": list(range(38, 44)),
    "Cognitive Engagement": list(range(44, 46)),
    "Disengagement": list(range(46, 49)),
    "Disengagement_Reversed": list(range(49, 52)),   # These are the indices after adding Reversed Disengagement
    "NASA-TLX": list(range(52, 58)),
    "NPS": [58]
}

## *Disengagement* Values Reversing

Since the *Disengagement* variable is the only one measured as: [ Good - Bad ], we reversed its scale.

In [5]:
def add_columns_at_position(df, pos, column_names, default_value=None):

    for i, col_name in enumerate(column_names):
        df.insert(pos + i, col_name, default_value)
    return df

new_columns = ['REV - Ero distratt* e non ho seguito la lezione.', 'REV - Durante la lezione ho lasciato che la mia mente vagasse.', 'REV - Ho fatto finta di seguire la lezione.']
df = add_columns_at_position(df, 49, new_columns, default_value=None)

df.iloc[:, variables_2["Disengagement_Reversed"]] = df.iloc[:, variables["Disengagement"]]
df.iloc[:, variables_2["Disengagement_Reversed"]]

,REV - Ero distratt* e non ho seguito la lezione.,REV - Durante la lezione ho lasciato che la mia mente vagasse.,REV - Ho fatto finta di seguire la lezione.
0,1,1,1
1,1,1,1
2,2,3,1
3,1,1,1
4,1,1,1
5,2,2,1
6,2,2,2
7,1,2,1
8,1,2,1
9,4,5,2
0,1,2,1
1,2,2,1
2,1,2,1
3,2,3,1
4,1,2,1
5,3,3,2
6,1,1,1
7,1,2,1
8,1,3,1
9,1,1,1
0,1,1,1
1,3,4,1
2,5,1,1
3,1,1,1
4,5,5,2
5,2,4,2
6,2,2,1
7,3,3,1
8,1,1,1
9,2,3,1

In [6]:
df.iloc[:, variables_2["Disengagement_Reversed"]] = df.iloc[:, variables_2["Disengagement_Reversed"]].replace({
    1: 7,
    2: 6,
    3: 5,
    4: 4,
    5: 3,
    6: 2,
    7: 1})

df.iloc[:, variables_2["Disengagement_Reversed"]]

/tmp/ipython-input-410193945.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.iloc[:, variables_2["Disengagement_Reversed"]] = df.iloc[:, variables_2["Disengagement_Reversed"]].replace({

,REV - Ero distratt* e non ho seguito la lezione.,REV - Durante la lezione ho lasciato che la mia mente vagasse.,REV - Ho fatto finta di seguire la lezione.
0,7,7,7
1,7,7,7
2,6,5,7
3,7,7,7
4,7,7,7
5,6,6,7
6,6,6,6
7,7,6,7
8,7,6,7
9,4,3,6
0,7,6,7
1,6,6,7
2,7,6,7
3,6,5,7
4,7,6,7
5,5,5,6
6,7,7,7
7,7,6,7
8,7,5,7
9,7,7,7
0,7,7,7
1,5,4,7
2,3,7,7
3,7,7,7
4,3,3,6
5,6,4,6
6,6,6,7
7,5,5,7
8,7,7,7
9,6,5,7

## Creation of the ID Row

The row contains an ID for each question related to their variable

In [7]:
acronyms = {
    "Learning Outcome": "LO",
    "Self Efficacy": "SE",
    "Immersiveness": "IM",
    "Affective Engagement": "AE",
    "Behavioral Engagement": "BE",
    "Cognitive Engagement": "CE",
    "Disengagement": "DE",
    "Disengagement_Reversed": "RDE",
    "NASA-TLX": "NTLX",
    "NPS": "NPS"
}

question_id = []

for key, value in variables_2.items():
    for i in range(len(value)):
        question_id.append(f"{acronyms[key]}{i + 1}")

question_id.append("Type") # This is for the "Dataset" column which does not correspond to any question
print(question_id)

['LO1', 'LO2', 'LO3', 'LO4', 'LO5', 'LO6', 'LO7', 'LO8', 'LO9', 'LO10', 'LO11', 'LO12', 'LO13', 'SE1', 'SE2', 'SE3', 'SE4', 'SE5', 'SE6', 'SE7', 'SE8', 'SE9', 'SE10', 'IM1', 'IM2', 'IM3', 'IM4', 'IM5', 'IM6', 'IM7', 'IM8', 'IM9', 'IM10', 'AE1', 'AE2', 'AE3', 'AE4', 'AE5', 'BE1', 'BE2', 'BE3', 'BE4', 'BE5', 'BE6', 'CE1', 'CE2', 'DE1', 'DE2', 'DE3', 'RDE1', 'RDE2', 'RDE3', 'NTLX1', 'NTLX2', 'NTLX3', 'NTLX4', 'NTLX5', 'NTLX6', 'NPS1', 'Type']

Now we include the array as the first row of the dataset.

In [8]:
question_id_df = pd.DataFrame([question_id], columns=df.columns)

df = pd.concat([question_id_df, df], ignore_index=True)

df

Warning: Total number of columns (60) exceeds max_columns (20). Falling back to pandas display.

,Cos'è il Social Debt?,Quale delle seguenti affermazioni descrive meglio un anti-pattern socio-tecnico?,Cosa sono i community smells?,Come differiscono i community smells dai code smells?,Qual è un esempio di community smell?,Quale affermazione sulla gestione del Social Debt è vera?,Qual è la principale differenza tra anti-pattern socio-tecnici e anti-pattern sociali,Cosa significa il termine 'Radio Silence' nel contesto dei community smells?,Vero o falso: Il Social Debt si riferisce solo ai costi finanziari di un progetto software.,Vero o falso: Gli anti-pattern socio-tecnici possono portare all'accumulo di Social Debt.,...,REV - Durante la lezione ho lasciato che la mia mente vagasse.,REV - Ho fatto finta di seguire la lezione.,Quanta attività mentale e percettiva ritieni sia stata richiesta durante la lezione? (Molto Semplice Da Seguire - Molto Impegnativa Da Seguire),Quanto è stata impegnativa fisicamente l’esperienza di seguire la lezione? (Molto Rilassante - Molto Faticosa),Come hai percepito il ritmo della lezione? Era lento o veloce? Sei riuscito/a a seguire l’esposizione dei concetti? (Nessuna Pressione - Molta Pressione),Valuta il tuo grado di soddisfazione riguardo alle tue prestazioni nell’ascoltare e comprendere la lezione (Massima Comprensione - Nessuna Comprensione),Quanto ti sei dovuto/a impegnare per mantenere un elevato livello di attenzione e comprensione durante la lezione? (Nessuno Sforzo - Massimo Sforzo),"Durante la lezione, come è variato il tuo livello di irritazione, stress e fastidio rispetto a quello di contentezza, relax e soddisfazione? (Massimo Relax - Massima Frustrazione)","Su una scala da 0 a 10, quante probabilità ci sono che parlerai positivamente di questa lezione sui 'Community Smells' a un amico o collega?",Dataset
0,LO1,LO2,LO3,LO4,LO5,LO6,LO7,LO8,LO9,LO10,...,RDE2,RDE3,NTLX1,NTLX2,NTLX3,NTLX4,NTLX5,NTLX6,NPS1,Type
1,1,1,1,1,1,1,1,1,1,1,...,7,7,9,10,10,10,8,10,10,Presence
2,1,1,1,1,1,1,1,1,1,1,...,7,7,8,10,7,3,7,9,8,Presence
3,1,1,1,1,1,1,1,1,0,1,...,5,7,9,9,10,9,8,10,8,Presence
4,1,1,1,1,1,1,1,0,0,1,...,7,7,9,10,10,10,9,10,8,Presence
5,0,1,1,1,1,1,1,1,1,1,...,7,7,9,10,8,9,10,9,10,Presence
6,1,1,1,1,1,1,1,1,1,0,...,6,7,9,9,10,9,9,10,10,Presence
7,1,1,1,1,1,1,1,1,1,1,...,6,6,10,10,10,10,10,10,9,Presence
8,1,1,1,1,1,1,1,1,1,1,...,6,7,6,7,7,8,8,8,7,Presence
9,1,1,1,1,1,1,1,1,1,1,...,6,7,5,9,6,9,5,9,8,Presence
10,1,1,1,1,1,1,1,1,1,1,...,3,6,6,7,7,8,5,6,8,Presence
11,1,1,1,1,1,1,1,1,1,1,...,6,7,9,10,10,8,9,10,9,Remote
12,1,1,1,1,1,1,1,1,1,1,...,6,7,9,9,10,9,9,10,8,Remote
13,1,1,1,1,1,1,1,1,1,1,...,6,7,8,9,9,9,9,8,8,Remote
14,1,0,1,1,1,1,1,1,1,0,...,5,7,8,9,5,4,7,9,2,Remote
15,1,1,1,1,1,1,1,1,1,1,...,6,7,4,9,6,10,7,9,8,Remote
16,1,1,1,1,1,1,1,1,0,1,...,5,6,5,7,10,3,8,10,8,Remote
17,1,1,1,1,1,1,1,1,1,1,...,7,7,4,10,7,9,9,10,9,Remote
18,1,1,1,1,1,1,1,1,1,1,...,6,7,6,7,8,9,8,7,9,Remote
19,1,1,1,1,1,1,1,1,0,1,...,5,7,4,8,6,8,9,10,7,Remote
20,1,1,1,1,1,1,1,1,1,1,...,7,7,9,9,10,9,9,9,9,Remote
21,1,1,1,1,1,1,1,0,1,1,...,7,7,9,10,10,10,10,10,10,VR
22,0,0,1,1,1,1,1,1,1,1,...,4,7,9,7,9,10,10,10,10,VR
23,1,1,1,1,1,1,1,1,0,1,...,7,7,4,4,10,8,4,4,10,VR
24,1,1,1,1,1,1,1,1,1,1,...,7,7,8,6,7,9,9,7,9,VR
25,1,1,1,1,1,1,1,1,1,1,...,3,6,7,9,9,7,5,8,9,VR
26,1,1,1,1,1,1,0,1,0,1,...,4,6,4,5,6,8,4,6,10,VR
27,1,1,1,1,1,1,1,1,0,1,...,6,7,6,7,8,4,6,10,10,VR
28,1,1,1,1,1,1,1,0,1,1,...,5,7,8,5,10,10,10,10,10,VR
29,1,1,1,1,1,1,1,1,1,1,...,7,7,5,10,8,10,10,8,6,VR
30,1,1,1,1,1,1,1,1,1,1,...,5,7,6,4,8,8,5,8,8,VR

## Column Drop

We will use this function to drop the columns based on their ID

In [9]:
def drop_column_by_first_row_value(df, value):
    col_to_drop = df.columns[df.iloc[0] == value]

    if not col_to_drop.empty:
        df = df.drop(columns=col_to_drop)

    return df


#df = drop_column_by_first_row_value(df, "CE1")

## CSV Save

In [10]:
df.to_csv(file_path+"dataset_for_test.csv", index=False)